### ISSUE TITLE
Name of the script

### ISSUE THREAD

**Issue by WorldLanguages** [WLandJBS/IsOnline-Userscript#4]
1. Where should the user put the studio ID? (to get last time) On the about me? What I'm working on? Location? Make it so the user can decide?

2. How to call the script? I could register a domain, like www.[name].tk so people write that domain on their about me/what im working on to tell the script that's the studio id. So it will be like this

_Anything here...
isonline.tk → [studioid]_

**Comment by WorldLanguages** [comment]
We can maybe make it so the studio where "isOnline" is removed has a special title.

So when going to a profile page, the script scans for all user's studios, to get the one called "www.name.tk".

I think that would be better, because the user wouldn't need to set their location to "not given", or waste space on their about me/working on.

**Comment by joker314** [comment]
Yes, the last idea is the best

**Comment by WorldLanguages** [comment]
What bout name?

**Comment by joker314** [comment]
`Activity Checker`?

**Comment by WorldLanguages** [comment]
Too technical...

isonline?

**Comment by joker314** [comment]
Ok; Sure

Shall we close then?
